{% set name = "sqlitecpp" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SRombauts/SQLiteCpp/archive/{{ version }}.tar.gz
  sha256: 5aa8eda130d0689bd5ed9b2074714c2dbc610f710483c61ba6cf944cebfe03af

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x' ) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - sqlite
    - gtest

test:
  commands:
    - test -f $PREFIX/lib/libSQLiteCpp${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/SQLiteCpp/Database.h  # [unix]

about:
  home: https://github.com/SRombauts/SQLiteCpp
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: SQLiteC++ (SQLiteCpp) is a smart and easy to use C++ SQLite3 wrapper.
  description: |
    SQLiteC++ offers an encapsulation around the native C APIs of SQLite, with
    a few intuitive and well documented C++ classes.

extra:
  recipe-maintainers:
    - wolfv
    - marimeireles
    - SylvainCorlay
    - JohanMabille
