context:
  name: sqlitecpp
  version: "3.3.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/SRombauts/SQLiteCpp/archive/${{ version }}.tar.gz
  sha256: 33bd4372d83bc43117928ee842be64d05e7807f511b5195f85d30015cad9cac6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - sqlite
    - gtest
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x' ) }}

tests:
  - package_contents:
      lib:
        - SQLiteCpp
      include:
        - SQLiteCpp/Database.h

about:
  homepage: https://github.com/SRombauts/SQLiteCpp
  license: MIT
  license_file: LICENSE.txt
  summary: SQLiteC++ (SQLiteCpp) is a smart and easy to use C++ SQLite3 wrapper.
  description: |
    SQLiteC++ offers an encapsulation around the native C APIs of SQLite, with
    a few intuitive and well documented C++ classes.

extra:
  recipe-maintainers:
    - wolfv
    - marimeireles
    - SylvainCorlay
    - JohanMabille
